osx_image: xcode8.2
language: objective-c
before_install:
  - bundle install
script:
  - xcodebuild build -workspace DangerDemo.xcworkspace -scheme DangerDemo -sdk iphonesimulator10.2
  - bundle exec danger
